### Obtener todos los proyectos

GET http://localhost:4000/api/projects/

### Obtener un producto

GET http://localhost:4000/api/projects/7

### Obtener todas las tareas

GET http://localhost:4000/api/tasks

### Crear nuevo proyecto

POST http://localhost:4000/api/projects
Content-Type: application/json

{
    "name": "project 5",
    "priority": 5,
    "description": "description of project 5"

}

### Actualizar un proyecto

PUT http://localhost:4000/api/projects/7
Content-Type: application/json

{

    "name": "project 5",
    "priority": 9,
    "description": "description of project 5"

}

### Borrar un proyecto

DELETE http://localhost:4000/api/projects/9

